name: "Clear Cloudflare Deployments"
description: "Action used to cleanup Cloudflare pages deployments"
author: "jeffplays2005"

inputs:
  CF_ACCOUNT_ID:
    description: "Cloudflare account ID"
    required: true
  CF_PROJECT_NAME:
    description: "Cloudflare project name"
    required: true
  CF_AUTH_TOKEN:
    description: "Cloudflare authentication token"
    required: true

runs:
  using: node24
  main: dist/index.js
