name: Clear cloudflare deployments

on:
  workflow_dispatch:

jobs:
  clear-cloudflare-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Clear cloudflare deployments
        uses: ./
        with:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
          CF_AUTH_TOKEN: ${{ secrets.CF_AUTH_TOKEN }}
